spring:
  application:
    name: MovieFlix

  datasource:
    url: jdbc:mysql://localhost:3306/movieflix?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 3649Dd109@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false